# Generated by Django 4.0.6 on 2023-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, verbose_name='服务器地址')),
                ('port', models.CharField(max_length=128, verbose_name='端口号')),
                ('user', models.CharField(max_length=128, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('date_time', models.DateTimeField(verbose_name='服务器时间')),
            ],
        ),
    ]
