# Generated by Django 4.0.6 on 2023-05-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_data', '0002_time_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time_date',
            new_name='hostinfo',
        ),
    ]
