# Generated by Django 4.0.6 on 2023-05-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_data', '0003_rename_time_date_hostinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostinfo',
            table='hostinfo',
        ),
    ]
